CREATE DATABASE wsa;

CREATE TABLE wsa.player (
	ID SMALLINT(5) UNSIGNED AUTO_INCREMENT,
	FirstName VARCHAR(50) DEFAULT '',
	Surname VARCHAR(50) DEFAULT '',
	OBJ_VERSION SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (ID)
) ENGINE=INNODB;

CREATE TABLE wsa.`match` (
    ID SMALLINT(5) UNSIGNED AUTO_INCREMENT,
    FK_PlayerOneID SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
    FK_PlayerTwoID SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
    OBJ_VERSION SMALLINT(5) UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
) ENGINE=INNODB;